---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

  - name: travis
    type: docker-image
    source:
      repository: rbakergds/travis-resource
      tag: latest

resources:
  - name: govuk-coronavirus-vulnerable-people-form
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form
      branch: master

  - name: govuk-coronavirus-vulnerable-people-form-travis-build
    type: travis
    icon: sync
    source:
      repository: alphagov/govuk-coronavirus-vulnerable-people-form
      travis-token: ((travis-api-token))
      branch: master
      pro: true

jobs:
  - name: deploy-to-staging
    serial: true
    plan:
      - get: govuk-coronavirus-vulnerable-people-form-travis-build
        trigger: true
      - get: govuk-coronavirus-vulnerable-people-form
      - task: paas-staging
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: latest
          inputs:
            - name: govuk-coronavirus-vulnerable-people-form
              path: src
          params:
            CF_API: https://api.cloud.service.gov.uk
            CF_USERNAME: ((paas-username))
            CF_PASSWORD: ((paas-password))
            CF_ORG: govuk_development
            CF_SPACE: staging
            BASIC_AUTH_PASSWORD: ((basic-auth-password))
            AWS_ACCESS_KEY_ID: ((aws-access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
          run:
            dir: src
            path: sh
            args:
              - '-c'
              - |
                set -eu

                cf api "$CF_API"
                cf auth
                cf t -o "$CF_ORG" -s "$CF_SPACE"
                cf v3-create-app govuk-coronavirus-vulnerable-people-form || true
                cf v3-apply-manifest -f manifest.yml

                cf set-env govuk-coronavirus-vulnerable-people-form BASIC_AUTH_PASSWORD "$BASIC_AUTH_PASSWORD"
                cf set-env govuk-coronavirus-vulnerable-people-form AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
                cf set-env govuk-coronavirus-vulnerable-people-form AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"

                cf set-env govuk-coronavirus-vulnerable-people-form SENTRY_DSN "$SENTRY_DSN"

                cf v3-zdt-push govuk-coronavirus-vulnerable-people-form --wait-for-deploy-complete --no-route
                cf map-route govuk-coronavirus-vulnerable-people-form cloudapps.digital --hostname govuk-coronavirus-vulnerable-people-form-stg

  - name: smoke-test-staging
    plan:
      - get: govuk-coronavirus-vulnerable-people-form
        trigger: true
        passed: [deploy-to-staging]
      - task: smoke-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/curl-ssl
          run:
            # TODO we can come up with a more thorough test than this
            path: curl
            args: ['--fail', '--silent', '--verbose', '--user', 'gds:((basic-auth-password))', 'https://govuk-coronavirus-vulnerable-people-form-stg.cloudapps.digital/']
