platform: linux
image_resource:
  type: docker-image
  source:
    # TODO: This container needs to include Chrome, otherwise capybara/apparition won't work
    repository: ruby
    tag: 2.6.5
params:
  TEST_URL:
inputs:
  - name: govuk-coronavirus-vulnerable-people-form
    path: src
caches:
  - path: vendor/bundle
run:
  path: sh
  dir: src
  args:
    - '-c'
    - |
      set -eu

      bundle install --path ../vendor/bundle
      bundle exec rails cucumber
