platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: govuk-coronavirus-vulnerable-people-form-feature-tests
params:
  TEST_URL:
inputs:
  - name: govuk-coronavirus-vulnerable-people-form
run:
  path: rails
  dir: govuk-coronavirus-vulnerable-people-form
  args: ['cucumber']
