platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/curl-ssl
params:
  URL:
run:
  path: sh
  args:
    - '-c'
    - |
      set -eu

      # TODO we can come up with a more thorough test than this
      curl --fail --silent --verbose --user gds:((basic-auth-password)) "$URL"
